export const TableData:Array<any> = [
  {
    'name': 'T124',
    'revision': "a01",
    'module': 'E1855',
    'module-sku': '0839',
    'chip-sku': '< DC >',
    'module-revision': '< DC >',
    'register-type':'Software',
    'block':`<a href="#">DAM1</a>`,
    'manual':'ardam.prod',
    'baseboard':'baset-tegra'
  },
  {
    'name': 'T124',
    'revision': "a01",
    'module': 'E1855',
    'module-sku': '0839',
    'chip-sku': '< DC >',
    'module-revision': '< DC >',
    'register-type':'Software',
    'block':`<a href="#">XUSB_PADCTL</a>`,
    'manual':'ardam.prod',
    'baseboard':'baset-tegra'
  },
  {
    'name': 'T124',
    'revision': "a01",
    'module': 'E1855',
    'module-sku': '0839',
    'chip-sku': '< DC >',
    'module-revision': '< DC >',
    'register-type':'Software',
    'block':`<a href="#">XUSB_PADCTL</a>`,
    'manual':'ardam.prod',
    'baseboard':'baset-tegra'
  },
  {
    'name': 'T124',
    'revision': "a01",
    'module': 'E1855',
    'module-sku': '0839',
    'chip-sku': '< DC >',
    'module-revision': '< DC >',
    'register-type':'Software',
    'block':`<a href="#">DAM1</a>`,
    'manual':'ardam.prod',
    'baseboard':'baset-tegra'
  },
  {
    'name': 'T124',
    'revision': "a01",
    'module': 'E1855',
    'module-sku': '0839',
    'chip-sku': '< DC >',
    'module-revision': '< DC >',
    'register-type':'Software',
    'block':`<a href="#">DAM1</a>`,
    'manual':'ardam.prod',
    'baseboard':'baset-tegra'
  },
  {
    'name': 'T124',
    'revision': "a01",
    'module': 'E1855',
    'module-sku': '0839',
    'chip-sku': '< DC >',
    'module-revision': '< DC >',
    'register-type':'Software',
    'block':`<a href="#">DAM1</a>`,
    'manual':'ardam.prod',
    'baseboard':'baset-tegra'
  },
  {
    'name': 'T124',
    'revision': "a01",
    'module': 'E1855',
    'module-sku': '0839',
    'chip-sku': '< DC >',
    'module-revision': '< DC >',
    'register-type':'Software',
    'block':`<a href="#">DAM1</a>`,
    'manual':'ardam.prod',
    'baseboard':'baset-tegra'
  },
  {
    'name': 'T124',
    'revision': "a01",
    'module': 'E1855',
    'module-sku': '0839',
    'chip-sku': '< DC >',
    'module-revision': '< DC >',
    'register-type':'Software',
    'block':`<a href="#">DAM1</a>`,
    'manual':'ardam.prod',
    'baseboard':'baset-tegra'
  },
  {
    'name': 'T124',
    'revision': "a01",
    'module': 'E1855',
    'module-sku': '0839',
    'chip-sku': '< DC >',
    'module-revision': '< DC >',
    'register-type':'Software',
    'block':`<a href="#">DAM1</a>`,
    'manual':'ardam.prod',
    'baseboard':'baset-tegra'
  },
];

